version: "3.8"

services:
  postgres-auth:
    image: postgres:15
    container_name: postgres-auth
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data
      - ./backups:/backups

  postgres-vehicle:
    image: postgres:15
    container_name: postgres-vehicle
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vehicle_db
    ports:
      - "5433:5432"
    volumes:
      - vehicle_data:/var/lib/postgresql/data

  postgres-traffic:
    image: postgres:15
    container_name: postgres-traffic
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: traffic_db
    ports:
      - "5434:5432"
    volumes:
      - traffic_data:/var/lib/postgresql/data

  postgres-incident:
    image: postgres:15
    container_name: postgres-incident
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: incident_db
    ports:
      - "5435:5432"
    volumes:
      - incident_data:/var/lib/postgresql/data

  postgres-notification:
    image: postgres:15
    container_name: postgres-notification
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notification_db
    ports:
      - "5436:5432"
    volumes:
      - notification_data:/var/lib/postgresql/data

volumes:
  auth_data:
  vehicle_data:
  traffic_data:
  incident_data:
  notification_data:
