services:

  # =========================
  # MYSQL DATABASE
  # =========================
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smart_traffic
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # =========================
  # BACKEND NODE + GRAPHQL
  # =========================
  backend:
    build: ./backend
    container_name: backend_api
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: smart_traffic

  # =========================
  # FRONTEND REACT
  # =========================
  frontend:
    build: ./frontend
    container_name: frontend_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data: